<?php

namespace AppBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function  rawSqlList(){
        $this->getEntityManager()->getConnection();
        $sql='select c.id,c.price,c.is_fulloption,m.name as make FROM car c join  make m on (c.make_id=m.id) ';
        $statement = $this->getEntityManager()->getConnection()->prepare($sql);
        // Set parameters
        // $statement->bindValue('status', 1);
        $statement->execute();
        return $statement->fetchAll();
    }

    public function optimizeQueryFind(){
        $qb=$this->createQueryBuilder('c');
        $qb->select('c');
        $qb->join('c.make','make');
        return $qb->getQuery()->getResult();
    }

    public function optimizeQueryFindID($id){
        $qb=$this->createQueryBuilder('c');
        $qb->select('c');
        $qb->join('c.make','make');
        $qb->where('c.id=:id');
        $qb->setParameter('id',$id);
        return $qb->getQuery()->getSingleResult();
    }


}
