<?php

namespace AppBundle\Repository;

/**
 * MakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MakeRepository extends \Doctrine\ORM\EntityRepository
{
}
